/**
 * Supabase database types — auto-generated from schema.
 *
 * DO NOT edit this file manually.
 * Regenerate after Phase 2 schema migration with:
 *   npx supabase gen types typescript --local > src/lib/types/database.ts
 *
 * This placeholder satisfies TypeScript until the schema exists.
 */
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
